### ISSUE TITLE
Not able to run `create-user`

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [whpptjs/whppt-api-express#17]
**Describe the bug**
`yarn run create-user` returns the following error
```
🚀 Please enter the details of the Root user you want to create! 🚀 
(node:68564) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@whppt/api-express version: 2.0.0-rc27
@whppt/nuxt version: 2.0.0-rc46
nuxt version: 2.14.12
node version: 14.15.0

**To Reproduce**
As above

**Expected behavior**
Be able to create a user

**Screenshots**
N/A

Desktop (please complete the following information):

OS: macOS 10.15.7 (19H524)
Browser: Chrome
Version: 89.0.4389.114
Smartphone (please complete the following information):
N/A

**Comment by lvcasjm** [comment]
Hey, 

This one has been actioned on and fixed, see this [commit](https://github.com/whpptjs/whppt-api-express/commit/25600d60a0f8cee796c362910f08f69d78b654e4). Its also been released into the next release candidate found [here](https://www.npmjs.com/package/@whppt/api-express/v/2.0.0-rc28).

Thanks for opening this issue
